# parameters.toml
dir_path_in = "path/to/your/directory/best_nanoloops"
dir_path_out = null
dir_path_in_props = null
verbose = true
show_plots = true
save = false

[user_pars]
nb clusters off = 4
nb clusters on = 4
nb clusters coupled = 4
