dir_path_in = "path/to/your/directory"
verbose = true
show_plots = true
save = false

[user_pars]
mode = "off"
func = "sigmoid"
method = "least_square"
asymmetric = false
"inf thresh" = 10
"sat thresh" = 90
"del 1st loop" = true
"pha corr" = "offset"
"pha fwd" = 0
"pha rev" = 180
"pha func" = "np.cos"
"main elec" = true
"sat mode" = "set"
"interp fact" = 4
"interp func" = "linear"

[user_pars.mask]
"revert mask" = false

[user_pars."diff domain"]
min = -5.0
max = 5.0

[user_pars."sat domain"]
min = -9.0
max = 9.0

[user_pars.mask.ref]
prop = "charac tot fit: area"
mode = "off"
"min val" = 0.005
fmt = ".2f"
interactive = false
